"""Agent-facing API."""

from .api import (
    add_artifact_to_package,
    diff,
    execute,
    execute_to_signals,
    explain_ir,
    explain_trace,
    fingerprint,
    fork,
    kernel_plan,
    lock,
    mutate,
    package,
    promote,
    recipe_expand,
    recipes,
    search,
    tagspec_get,
    tagspec_verify,
    unpack,
    validate,
    verify,
    verify_package,
    vocabulary,
)
from .discover import discover

__all__ = [
    "add_artifact_to_package",
    "diff",
    "discover",
    "execute",
    "execute_to_signals",
    "explain_ir",
    "explain_trace",
    "fingerprint",
    "fork",
    "kernel_plan",
    "lock",
    "mutate",
    "package",
    "promote",
    "recipe_expand",
    "recipes",
    "search",
    "tagspec_get",
    "tagspec_verify",
    "unpack",
    "validate",
    "verify",
    "verify_package",
    "vocabulary",
]
