"""Token System v2 Decision Algebra."""

from quant_strategy_tokenizer.decision_v2.migration import (
    LegacyDecisionKind,
    LegacyDecisionMapping,
    LegacyReduceMigration,
    classify_legacy_decision_reduce,
    map_legacy_decision_kind,
)
from quant_strategy_tokenizer.decision_v2.model import (
    DECISION_AGGREGATOR_SCHEMA_VERSION,
    DECISION_FOLD_POLICY_SCHEMA_VERSION,
    DECISION_MONOID_SCHEMA_VERSION,
    DECISION_SCHEMA_VERSION,
    FINAL_UNKNOWN_AS_ACCEPT_REASON,
    FINAL_UNKNOWN_AS_REJECT_REASON,
    DecisionAggregatorId,
    DecisionAggregatorSpec,
    DecisionCombineResult,
    DecisionFoldPolicyId,
    DecisionFoldPolicySpec,
    DecisionKind,
    DecisionMonoidId,
    DecisionMonoidSpec,
    DecisionScorePolicy,
    DecisionV2,
)
from quant_strategy_tokenizer.decision_v2.reference import (
    aggregate_decisions,
    combine_decisions,
    fold_decisions,
    is_aggregator_id,
    is_fold_policy_id,
    is_monoid_id,
)
from quant_strategy_tokenizer.decision_v2.token_pack import (
    DECISION_ALGEBRA_PACK_ID,
    DECISION_ALGEBRA_PACK_VERSION,
    DecisionAlgebraCategory,
    decision_algebra_token_pack_v2,
)

__all__ = [
    "DECISION_AGGREGATOR_SCHEMA_VERSION",
    "DECISION_ALGEBRA_PACK_ID",
    "DECISION_ALGEBRA_PACK_VERSION",
    "DECISION_FOLD_POLICY_SCHEMA_VERSION",
    "DECISION_MONOID_SCHEMA_VERSION",
    "DECISION_SCHEMA_VERSION",
    "FINAL_UNKNOWN_AS_ACCEPT_REASON",
    "FINAL_UNKNOWN_AS_REJECT_REASON",
    "DecisionAggregatorId",
    "DecisionAggregatorSpec",
    "DecisionAlgebraCategory",
    "DecisionCombineResult",
    "DecisionFoldPolicyId",
    "DecisionFoldPolicySpec",
    "DecisionKind",
    "DecisionMonoidId",
    "DecisionMonoidSpec",
    "DecisionScorePolicy",
    "DecisionV2",
    "LegacyDecisionKind",
    "LegacyDecisionMapping",
    "LegacyReduceMigration",
    "aggregate_decisions",
    "classify_legacy_decision_reduce",
    "combine_decisions",
    "decision_algebra_token_pack_v2",
    "fold_decisions",
    "is_aggregator_id",
    "is_fold_policy_id",
    "is_monoid_id",
    "map_legacy_decision_kind",
]
